// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./components/Address.vue')['default']
    BaseButton: typeof import('./components/button/BaseButton.vue')['default']
    Contract: typeof import('./components/Contract.vue')['default']
    ContractUI: typeof import('./components/ContractUI.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    'IIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IIc:baselineLogout': typeof import('~icons/ic/baseline-logout')['default']
    'IIc:baselineSwitchAccessShortcut': typeof import('~icons/ic/baseline-switch-access-shortcut')['default']
    IIcBaselineContentCopy: typeof import('~icons/ic/baseline-content-copy')['default']
    IIcBaselineKeyboardArrowDown: typeof import('~icons/ic/baseline-keyboard-arrow-down')['default']
    IIcBaselineKeyboardArrowUp: typeof import('~icons/ic/baseline-keyboard-arrow-up')['default']
    IIcBaselineOpenInNew: typeof import('~icons/ic/baseline-open-in-new')['default']
    'ISvgSpinners:3DotsFade': typeof import('~icons/svg-spinners/3-dots-fade')['default']
    NetworkStatus: typeof import('./components/NetworkStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TxButton: typeof import('./components/button/TxButton.vue')['default']
    UserStatus: typeof import('./components/UserStatus.vue')['default']
  }
}
