// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./components/Address.vue')['default']
    ApplyContract: typeof import('./components/ApplyContract.vue')['default']
    Contract: typeof import('./components/Contract.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IIcAdd: typeof import('~icons/ic/add')['default']
    IIcArrowDown: typeof import('~icons/ic/arrow-down')['default']
    IIcBaselineKeyboardArrowDown: typeof import('~icons/ic/baseline-keyboard-arrow-down')['default']
    IIcBaselineKeyboardArrowUp: typeof import('~icons/ic/baseline-keyboard-arrow-up')['default']
    IIcBaselineOpenInNew: typeof import('~icons/ic/baseline-open-in-new')['default']
    IIcBaseLineOpenInNew: typeof import('~icons/ic/base-line-open-in-new')['default']
    IIcClose: typeof import('~icons/ic/close')['default']
    IIcDown: typeof import('~icons/ic/down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
